---
title: "Academic CV"
description: |
  I am currently School Manager of Te Kawa a Māui at Te Herenga Waka–Victoria University of Wellington. I most recently completed my BA(Hons) in Māori Studies, examining the phenomenon of whakamā in the language learning context. My research interests are in Māori and indigenous psychologies with a background in both quantitative and qualitative research methods.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# Academic history
*Victoria University of Wellington*  
**2019 – Present** BSc(Hons) Psychology  
**2019 – Present** GDipSc Statistics  
**2014 – 2019** BA(Hons) Māori Studies  
**2008 – 2013** BA Māori Studies and Education  
**2008 – 2013** BSc Psychology  

# Employment history
**2020 – Present** School Manager, Te Kawa a Māui  
**2015 – 2020** Student Adviser – Equity and Engagement, FHSS  
**2013 & 2014**	Summer Research Scholarships, Te Kawa a Māui  
**2011 – 2014**	Tutor, Te Kawa a Māui  
**2011 – 2014**	Marae Assistant, Te Herenga Waka  

# Research skills
**Kaupapa Māori research.** I have experience in kaupapa Māori research gained through two summer research scholarships and my Honours project in Māori Studies. Both research scholarships were supervised by Professor Rāwinia Higgins for the Te Kura Roa project on community initiatives for the revitalisation of te reo Māori. My Honours project was supervised by Dr Awanui Te Huia, and involved interviews with heritage learners of te reo Māori on how they navigated experiences of whakamā within the language learning context.  
**Statistical analysis with R.** I have started to develop proficiency in conducting statistical analysis using R programming. My current research project involves a moderation analysis of the relationship between intergroup/intragroup discrimination and ethnic identity in Māori, as influenced by the level of prototypicality to the group category.